from telebot import types

start_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=3)
btn1 = types.KeyboardButton('Фэнтези')
btn2 = types.KeyboardButton('Научная фантастика')
btn3 = types.KeyboardButton('Хоррор')
btn4 = types.KeyboardButton('Комикс')
btn5 = types.KeyboardButton('Смесь жанров')
btn6 = types.KeyboardButton('Другое')
start_markup.add(btn1, btn2, btn3, btn4, btn5, btn6)

comic_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=3)
btn1 = types.KeyboardButton('Постмодернизм')
btn2 = types.KeyboardButton('Мистика')
btn3 = types.KeyboardButton('Странное будущее')
btn4 = types.KeyboardButton('Начать с начала')
comic_markup.add(btn1, btn2, btn3, btn4)

comic_post_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('... супергероях')
btn2 = types.KeyboardButton('... литературе')
btn3 = types.KeyboardButton('Обратно к выбору направления')
btn4 = types.KeyboardButton('Начать с начала')
comic_post_markup.add(btn1, btn2, btn3, btn4)

comic_mist_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Детектив с вредными привычками')
btn2 = types.KeyboardButton('Дом с необычными ключами')
btn3 = types.KeyboardButton('Обратно к выбору направления')
btn4 = types.KeyboardButton('Начать с начала')
comic_mist_markup.add(btn1, btn2, btn3, btn4)

comic_fut_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Ядрёная сатира')
btn2 = types.KeyboardButton('Мир без мужчин')
btn3 = types.KeyboardButton('Обратно к выбору направления')
btn4 = types.KeyboardButton('Начать с начала')
comic_fut_markup.add(btn1, btn2, btn3, btn4)

horror_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Вампиры')
btn2 = types.KeyboardButton('Зомби и что-то вроде')
btn3 = types.KeyboardButton('Оборотни')
btn4 = types.KeyboardButton('Призраки')
btn5 = types.KeyboardButton('Боги и демоны')
btn6 = types.KeyboardButton('Начать с начала')
horror_markup.add(btn1, btn2, btn3, btn4, btn5, btn6)

horror_1_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Знаковый роман XIX века')
btn2 = types.KeyboardButton('Знаковый роман XX века')
btn3 = types.KeyboardButton('Знаковый роман XXI века')
btn4 = types.KeyboardButton('Вампирский постмодернизм')
btn5 = types.KeyboardButton('Обратно к выбору существ')
btn6 = types.KeyboardButton('Начать с начала')
horror_1_markup.add(btn1, btn2, btn3, btn4, btn5, btn6)

horror_2_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=3)
btn1 = types.KeyboardButton('Масштаб')
btn2 = types.KeyboardButton('Одиночество')
btn3 = types.KeyboardButton('Драма')
btn4 = types.KeyboardButton('Обратно к выбору существ')
btn5 = types.KeyboardButton('Начать с начала')
horror_2_markup.add(btn1, btn2, btn3, btn4, btn5)

horror_3_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=3)
btn1 = types.KeyboardButton('... шпионском триллере')
btn2 = types.KeyboardButton('... короткой повести')
btn3 = types.KeyboardButton('... мужской мелодраме')
btn4 = types.KeyboardButton('Обратно к выбору существ')
btn5 = types.KeyboardButton('Начать с начала')
horror_3_markup.add(btn1, btn2, btn3, btn4, btn5)

horror_4_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Нехороший дом')
btn2 = types.KeyboardButton('Скелеты в шкафах')
btn3 = types.KeyboardButton('Обратно к выбору существ')
btn4 = types.KeyboardButton('Начать с начала')
horror_4_markup.add(btn1, btn2, btn3, btn4)

horror_5_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=3)
btn1 = types.KeyboardButton('Исторический роман')
btn2 = types.KeyboardButton('Кровавый триллер')
btn3 = types.KeyboardButton('Неспешная мистика')
btn4 = types.KeyboardButton('Обратно к выбору существ')
btn5 = types.KeyboardButton('Начать с начала')
horror_5_markup.add(btn1, btn2, btn3, btn4, btn5)

fanscifi_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Прошлое')
btn2 = types.KeyboardButton('Будущее')
btn3 = types.KeyboardButton('Начать с начала')
fanscifi_markup.add(btn1, btn2, btn3)

fanscifi_1_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Да!')
btn2 = types.KeyboardButton('Нет.')
btn3 = types.KeyboardButton('Начать с начала')
fanscifi_1_markup.add(btn1, btn2, btn3)

fanscifi_2_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Пожалуй')
btn2 = types.KeyboardButton('Неа')
btn3 = types.KeyboardButton('Начать с начала')
fanscifi_2_markup.add(btn1, btn2, btn3)

fanscifi_2_2_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Умирающее Солнце')
btn2 = types.KeyboardButton('Демон из шипов и лезвий')
btn3 = types.KeyboardButton('Начать с начала')
fanscifi_2_2_markup.add(btn1, btn2, btn3)

other_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Можно')
btn2 = types.KeyboardButton('Да ну')
btn3 = types.KeyboardButton('Начать с начала')
other_markup.add(btn1, btn2, btn3)

other_love_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Любовь')
btn2 = types.KeyboardButton('Преодоление несправедливости')
btn3 = types.KeyboardButton('Начать с начала')
other_love_markup.add(btn1, btn2, btn3)

other_postmodern_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Мозговынос')
btn2 = types.KeyboardButton('Что-то попроще')
btn3 = types.KeyboardButton('Начать с начала')
other_postmodern_markup.add(btn1, btn2, btn3)

other_easier_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Антиутопия')
btn2 = types.KeyboardButton('Не антиутопия')
btn3 = types.KeyboardButton('Начать с начала')
other_easier_markup.add(btn1, btn2, btn3)

other_dys_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Военный тоталитаризм')
btn2 = types.KeyboardButton('Религиозный тоталитаризм')
btn3 = types.KeyboardButton('Постапокалипсис')
btn4 = types.KeyboardButton('Мир, сошедший с ума')
btn5 = types.KeyboardButton('Начать с начала')
other_dys_markup.add(btn1, btn2, btn3, btn4, btn5)

other_brain_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('С путешествиями во времени')
btn2 = types.KeyboardButton('Без них')
btn3 = types.KeyboardButton('Начать с начала')
other_brain_markup.add(btn1, btn2, btn3)

fantasy_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Похожее')
btn2 = types.KeyboardButton('Непохожее')
btn3 = types.KeyboardButton('Начать с начала')
fantasy_markup.add(btn1, btn2, btn3)

fantasy_lotr_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=1)
btn1 = types.KeyboardButton('Не настолько новичок')
btn2 = types.KeyboardButton('Начать с начала')
fantasy_lotr_markup.add(btn1, btn2)

fantasy_new_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=3)
btn1 = types.KeyboardButton('Новичок...')
btn2 = types.KeyboardButton('Возможно')
btn3 = types.KeyboardButton('Нет, конечно')
btn4 = types.KeyboardButton('Начать с начала')
fantasy_new_markup.add(btn1, btn2, btn3, btn4)

fantasy_artur_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Артур')
btn2 = types.KeyboardButton('Мерлин')
btn3 = types.KeyboardButton('Фея Моргана')
btn4 = types.KeyboardButton('Не люблю Артуриану')
btn5 = types.KeyboardButton('Начать с начала')
fantasy_artur_markup.add(btn1, btn2, btn3, btn4, btn5)

fantasy_modset_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=3)
btn1 = types.KeyboardButton('Да, конечно')
btn2 = types.KeyboardButton('Может быть')
btn3 = types.KeyboardButton('Совсем нет')
btn4 = types.KeyboardButton('Начать с начала')
fantasy_modset_markup.add(btn1, btn2, btn3, btn4)

fantasy_gods_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Боги')
btn2 = types.KeyboardButton('Люди под мостом')
btn3 = types.KeyboardButton('Начать с начала')
fantasy_gods_markup.add(btn1, btn2, btn3)

fantasy_dark_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=1)
btn1 = types.KeyboardButton('Только не вестерны')
btn2 = types.KeyboardButton('Начать с начала')
fantasy_dark_markup.add(btn1, btn2)

fantasy_animals_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Дракон')
btn2 = types.KeyboardButton('Кролик')
btn3 = types.KeyboardButton('Единорог')
btn4 = types.KeyboardButton('Не надо животных')
btn5 = types.KeyboardButton('Начать с начала')
fantasy_animals_markup.add(btn1, btn2, btn3, btn4, btn5)

fantasy_althis_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=3)
btn1 = types.KeyboardButton('Да, с романтикой')
btn2 = types.KeyboardButton('Да, с волшебством')
btn3 = types.KeyboardButton('Не хочу')
btn4 = types.KeyboardButton('Начать с начала')
fantasy_althis_markup.add(btn1, btn2, btn3, btn4)

fantasy_series_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Пираты')
btn2 = types.KeyboardButton('Летающие пираты')
btn3 = types.KeyboardButton('Сатира над бюрократией')
btn4 = types.KeyboardButton('Сатира над религией')
btn5 = types.KeyboardButton('Игра слов')
btn6 = types.KeyboardButton('Не интересно')
btn7 = types.KeyboardButton('Начать с начала')
fantasy_series_markup.add(btn1, btn2, btn3, btn4, btn5, btn6, btn7)

fantasy_withend_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Важно')
btn2 = types.KeyboardButton('Не важно')
btn3 = types.KeyboardButton('Начать с начала')
fantasy_withend_markup.add(btn1, btn2, btn3)

fantasy_pops_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Возвышенное')
btn2 = types.KeyboardButton('Приземлённое')
btn3 = types.KeyboardButton('Начать с начала')
fantasy_pops_markup.add(btn1, btn2, btn3)

fantasy_standart_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Волшебники')
btn2 = types.KeyboardButton('Варвары')
btn3 = types.KeyboardButton('Тёмные эльфы')
btn4 = types.KeyboardButton('Что-то нетривиальное')
btn5 = types.KeyboardButton('Начать с начала')
fantasy_standart_markup.add(btn1, btn2, btn3, btn4, btn5)

fantasy_trilogy_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('... о ворах')
btn2 = types.KeyboardButton('... об ассасинах')
btn3 = types.KeyboardButton('... о магах')
btn4 = types.KeyboardButton('... о макгаффине')
btn5 = types.KeyboardButton('... трилогий')
btn6 = types.KeyboardButton('Не надо трилогии')
btn7 = types.KeyboardButton('Начать с начала')
fantasy_trilogy_markup.add(btn1, btn2, btn3, btn4, btn5, btn6, btn7)

fantasy_more_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Сойдёт')
btn2 = types.KeyboardButton('Мало')
btn3 = types.KeyboardButton('Начать с начала')
fantasy_more_markup.add(btn1, btn2, btn3)

fantasy_greatevil_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Земля в тенях')
btn2 = types.KeyboardButton('Запутанное повествование')
btn3 = types.KeyboardButton('Единая Сила')
btn4 = types.KeyboardButton('Искатель Истины')
btn5 = types.KeyboardButton('Начать с начала')
fantasy_greatevil_markup.add(btn1, btn2, btn3, btn4, btn5)

scifi_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=3)
btn1 = types.KeyboardButton('Нырнём в киберпанк')
btn2 = types.KeyboardButton('Полетим в космос')
btn3 = types.KeyboardButton('Останемся на Земле')
btn4 = types.KeyboardButton('Начать с начала')
scifi_markup.add(btn1, btn2, btn3, btn4)

scifi_cyber_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Нуар')
btn2 = types.KeyboardButton('Самураи')
btn3 = types.KeyboardButton('Неовикторианский стиль')
btn4 = types.KeyboardButton('Не киберпанк, но почти')
btn5 = types.KeyboardButton('Начать с начала')
scifi_cyber_markup.add(btn1, btn3, btn2, btn4, btn5)

scifi_earth_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=3)
btn1 = types.KeyboardButton('Под землю')
btn2 = types.KeyboardButton('Под воду')
btn3 = types.KeyboardButton('Поверхность лучше')
btn4 = types.KeyboardButton('Начать с начала')
scifi_earth_markup.add(btn1, btn2, btn3, btn4)

scifi_science_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Коммунизм')
btn2 = types.KeyboardButton('Феминизм')
btn3 = types.KeyboardButton('Гуманизм')
btn4 = types.KeyboardButton('Католицизм')
btn5 = types.KeyboardButton('Философия')
btn6 = types.KeyboardButton('Иные направления')
btn7 = types.KeyboardButton('Начать с начала')
scifi_science_markup.add(btn1, btn2, btn3, btn4, btn5, btn6, btn7)

scifi_dif_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Современная хроноопера')
btn2 = types.KeyboardButton('Классическая хроноопера')
btn3 = types.KeyboardButton('Фантастический триллер')
btn4 = types.KeyboardButton('Фантастический детектив')
btn5 = types.KeyboardButton('Начать с начала')
scifi_dif_markup.add(btn1, btn3, btn2, btn4, btn5)

scifi_space_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Далеко-далеко')
btn2 = types.KeyboardButton('Марс и чуть дальше')
btn3 = types.KeyboardButton('Начать с начала')
scifi_space_markup.add(btn1, btn2, btn3)

scifi_mars_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Отрывочные сведения')
btn2 = types.KeyboardButton('Перевёрнутый мир')
btn3 = types.KeyboardButton('Одиссея')
btn4 = types.KeyboardButton('Производственный роман')
btn5 = types.KeyboardButton('Начать с начала')
scifi_mars_markup.add(btn1, btn2, btn3, btn4, btn5)

scifi_war_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=3)
btn1 = types.KeyboardButton('Война!')
btn2 = types.KeyboardButton('Хм...')
btn3 = types.KeyboardButton('Не надо войны')
btn4 = types.KeyboardButton('Начать с начала')
scifi_war_markup.add(btn1, btn2, btn3, btn4)

scifi_enemy_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Всех со всеми')
btn2 = types.KeyboardButton('Людей с насекомыми')
btn3 = types.KeyboardButton('Людей с людьми')
btn4 = types.KeyboardButton('Людей с чужими')
btn5 = types.KeyboardButton('Людей с непонятно кем')
btn6 = types.KeyboardButton('Претендентов на власть')
btn7 = types.KeyboardButton('Начать с начала')
scifi_enemy_markup.add(btn1, btn2, btn3, btn4, btn5, btn6, btn7)

scifi_humor_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=3)
btn1 = types.KeyboardButton('Больше юмора')
btn2 = types.KeyboardButton('Меньше юмора')
btn3 = types.KeyboardButton('Без юмора')
btn4 = types.KeyboardButton('Начать с начала')
scifi_humor_markup.add(btn1, btn2, btn3, btn4)

scifi_contact_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('С упором')
btn2 = types.KeyboardButton('Без упора')
btn3 = types.KeyboardButton('Начать с начала')
scifi_contact_markup.add(btn1, btn2, btn3)

scifi_alien_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=3)
btn1 = types.KeyboardButton('Мирные')
btn2 = types.KeyboardButton('Заботливые')
btn3 = types.KeyboardButton('Несуществующие')
btn4 = types.KeyboardButton('Враждебные')
btn5 = types.KeyboardButton('Слишком плодовитые')
btn6 = types.KeyboardButton('Начать с начала')
scifi_alien_markup.add(btn1, btn2, btn3, btn4, btn5, btn6)

scifi_last_markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
btn1 = types.KeyboardButton('Компьютерные науки')
btn2 = types.KeyboardButton('История')
btn3 = types.KeyboardButton('Инженерное дело')
btn4 = types.KeyboardButton('Мягкая научная фантастика в романах')
btn5 = types.KeyboardButton('Мягкая научная фантастика в рассказах')
btn6 = types.KeyboardButton('Начать с начала')
scifi_last_markup.add(btn1, btn2, btn3, btn4, btn5, btn6)